default_order:
  - "resting"
  - "emotion_face"
  - "sret"
  - "prt"
# resting -> speech -> facial recognition -> sleep -> sret -> prt

timing:
  iei: 30
  before_wait: 5

valid_id:
  ohc:
    - 2
    - 7
    - 9
    - 10
    - 12
    - 17
    - 20
    - 22
    - 23
    - 26
    - 27
    - 29
    - 31
    - 34
  omdd:
    - 3
    - 6
    - 11
    - 14
    - 21
    - 24
    - 25
    - 32
    - 35
