# TODO: 通过继承优化结构
defaults:
  - session: config
  - exps@exps.emotion_face.pre: emotion_face/pre
  - exps@exps.emotion_face.full: emotion_face/full
  - exps@exps.prt.pre: prt/pre
  - exps@exps.prt.full: prt/full
  - exps@exps.resting.full: resting/full
  - exps@exps.sret.full: sret/full
  - exps@exps.sret.pre: sret/pre

project_root: ${hydra:runtime.cwd}
pkg_root: ${project_root}/psycho
exps_dir: ${pkg_root}/exps
output_dir: ${project_root}/data
# xdf 分析结果目录
result_dir: ${output_dir}/results

log_level: INFO
debug: false

labrecorder:
  host: localhost
  port: 22345

hydra:
  run:
    dir: . # 不创建新的输出目录
  output_subdir: null # 不创建 outputs/ 子目录
  job:
    chdir: false
  hydra_logging:
    version: 1
    root:
      handlers: null # 禁止 hydra 自身 logger
    loggers:
      hydra:
        handlers: null
  sweep:
    dir: .
