defaults:
  - pilot@_here_
  - exps@exps.emotion_face.pre: emotion_face/pre
  - exps@exps.prt.pre: prt/pre
  - exps@exps.sret.pre: sret/pre
  - override exps@exps.emotion_face.full: emotion_face/full
  - override exps@exps.prt.full: prt/full
  - override exps@exps.sret.full: sret/full
  - override exps@exps.resting.full: resting/full
  - _self_

output_dir: ${project_root}/data
# xdf 分析结果目录
result_dir: ${output_dir}/results
